CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('OWNER', 'ADMIN')),
  created_by INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS referrals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  role_granted TEXT NOT NULL CHECK (role_granted IN ('OWNER', 'ADMIN')),
  created_by INTEGER NOT NULL,
  is_used INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sdk_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  engine TEXT NOT NULL CHECK (engine IN ('MUNDO', 'BCORE')),
  sdk_key TEXT UNIQUE NOT NULL,
  duration_days INTEGER NOT NULL,
  pkg_limit INTEGER NOT NULL,
  app_limit INTEGER NOT NULL,
  feature1 INTEGER DEFAULT 0,
  feature2 INTEGER DEFAULT 0,
  is_blocked INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
